# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy project files
COPY . /app

# Create a setup.cfg to specify only the weather module for installation
RUN echo "[metadata]\nname = weather\n\n[options]\npy_modules = weather" > setup.cfg

# Install dependencies in editable mode
RUN pip install --no-cache-dir -e .

# Set environment variables
ENV ENV=production
ENV LOG_LEVEL=INFO
ENV APP_VERSION=0.1.0

# Launch the MCP server
CMD [ "python", "weather.py" ]
